// src/lib/components/HostView.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    Check,
    CircleAlert,
    CircleCheck,
    Copy,
    HousePlus,
    LoaderCircle,
    Square,
  } from "@lucide/svelte";
  import {
    getLanScan,
    probeHostPort,
    startHost,
    startLanScan,
    stopLanScan,
    stopTunnel,
  } from "@api/p2p";
  import { backendMessage, t } from "@i18n";
  import type { HostUriLifetime } from "@models/preferences";
  import type { P2pStatus } from "@models/p2p";
  import Button from "./ui/Button.svelte";
  import Input from "./ui/Input.svelte";
  import Select, { type Option } from "./ui/Select.svelte";

  let { status, uriLifetime, onLifetime } = $props<{
    status: P2pStatus;
    uriLifetime: HostUriLifetime;
    onLifetime: (value: HostUriLifetime) => void;
  }>();
  let portMode = $state("auto");
  let manualPort = $state("25565");
  let maxPlayers = $state("");
  let scan = $state({ scanning: false, port: null as number | null });
  let scanError = $state("");
  let commandError = $state("");
  let pending = $state(false);
  let copied = $state(false);
  let scanTimer: number | null = null;
  let monitorTimer: number | null = null;
  let previousPhase = $state<P2pStatus["phase"] | null>(null);
  const portOptions = $derived<Option[]>([
    { label: t("create.automaticDiscovery"), value: "auto" },
    { label: t("create.manual"), value: "manual" },
  ]);
  const lifetimeOptions = $derived<Option[]>(
    ["always", "never", "1h", "3h", "6h", "12h", "24h"].map((value) => ({
      label: t(
        `create.lifetime${value === "always" ? "Always" : value === "never" ? "Never" : value}`,
      ),
      value,
    })),
  );
  let hosting = $derived(status.mode === "host" && status.phase !== "idle");
  let occupied = $derived(status.phase !== "idle" && status.mode !== "host");
  let selectedPort = $derived(portMode === "auto" ? scan.port : Number(manualPort));
  let validPort = $derived(
    Number.isInteger(selectedPort) &&
      selectedPort != null &&
      selectedPort >= 1 &&
      selectedPort <= 65535,
  );
  let validMaxPlayers = $derived(
    maxPlayers.trim() === "" ||
      (Number.isInteger(Number(maxPlayers)) &&
        Number(maxPlayers) >= 1 &&
        Number(maxPlayers) <= 1000),
  );
  let canCreate = $derived(!pending && !occupied && validPort && validMaxPlayers);

  onMount(() => {
    if (status.phase === "idle") void beginScan();
    return () => {
      stopPolling();
      stopMonitoring();
      void stopLanScan().catch((error) => console.error("Failed to stop LAN scan", error));
    };
  });

  $effect(() => {
    const phase = status.phase;
    if (previousPhase === null) {
      previousPhase = phase;
      return;
    }
    if (phase === previousPhase) return;

    const wasIdle = previousPhase === "idle";
    previousPhase = phase;
    if (phase === "idle" && !wasIdle && portMode === "auto") {
      void beginScan(true);
    } else if (phase !== "idle") {
      void stopScan();
    }
  });

  function stopPolling(): void {
    if (scanTimer != null) {
      window.clearInterval(scanTimer);
      scanTimer = null;
    }
  }
  function stopMonitoring(): void {
    if (monitorTimer != null) {
      window.clearInterval(monitorTimer);
      monitorTimer = null;
    }
  }
  async function beginScan(restart = false): Promise<void> {
    stopPolling();
    stopMonitoring();
    scanError = "";
    try {
      scan = await startLanScan(restart);
      scanTimer = window.setInterval(pollScan, 800);
    } catch (error) {
      scanError = backendMessage(error);
    }
  }
  async function pollScan(): Promise<void> {
    try {
      scan = await getLanScan();
      if (scan.port != null || !scan.scanning) {
        stopPolling();
        if (scan.port != null) startMonitoring();
      }
    } catch (error) {
      scanError = backendMessage(error);
      stopPolling();
    }
  }
  function startMonitoring(): void {
    if (monitorTimer != null) return;
    monitorTimer = window.setInterval(async () => {
      if (scan.port == null) return;
      try {
        if (!(await probeHostPort(scan.port))) void beginScan(true);
      } catch (error) {
        scanError = backendMessage(error);
      }
    }, 5000);
  }
  async function stopScan(): Promise<void> {
    stopPolling();
    stopMonitoring();
    scan = { scanning: false, port: null };
    try {
      await stopLanScan();
    } catch (error) {
      scanError = backendMessage(error);
    }
  }
  function setPortMode(value: string): void {
    if (value !== "auto" && value !== "manual") return;

    portMode = value;
    if (value === "auto") void beginScan(true);
    else void stopScan();
  }
  async function createRoom(): Promise<void> {
    if (!canCreate || selectedPort == null) return;
    pending = true;
    commandError = "";
    try {
      await startHost(selectedPort, maxPlayers.trim() ? Number(maxPlayers) : null, uriLifetime);
    } catch (error) {
      commandError = backendMessage(error);
    } finally {
      pending = false;
    }
  }
  async function stopRoom(): Promise<void> {
    pending = true;
    try {
      await stopTunnel();
    } catch (error) {
      commandError = backendMessage(error);
    } finally {
      pending = false;
    }
  }
  async function copyInvite(): Promise<void> {
    if (!status.shareUri) return;
    await navigator.clipboard.writeText(status.shareUri);
    copied = true;
    window.setTimeout(() => (copied = false), 1600);
  }
</script>

<div class="workspace create-workspace">
  <section class="intro">
    <div>
      <h1>{hosting ? t("create.running") : t("create.title")}</h1>
      <p>{hosting ? t("create.runningHint") : t("create.idleHint")}</p>
    </div>
    <span class:active={hosting && status.phase === "active"} class="phase-pill"
      >{hosting
        ? status.phase === "active"
          ? t("create.created")
          : t("create.processing")
        : t("create.notCreated")}</span
    >
  </section>
  {#if hosting}
    <section class="connection-panel host-panel">
      <div class="share-block">
        <span>{t("create.invite")}</span><strong
          >{status.shareUri ?? t("create.generatingInvite")}</strong
        ><Button
          variant="outline"
          class="copy-button"
          disabled={!status.shareUri}
          onclick={copyInvite}
          >{#if copied}<Check size={16} />{t("create.copied")}{:else}<Copy size={16} />{t(
              "create.copyInvite",
            )}{/if}</Button
        >
      </div>
      <div class="host-summary">
        <div><span>{t("create.players")}</span><strong>{status.playerCount}</strong></div>
        <div><span>{t("create.targetPort")}</span><strong>{status.hostPort ?? "--"}</strong></div>
      </div>
      {#if status.hostPeers.length}<section class="host-peer-section">
          <div class="host-peer-heading">
            <span>{t("create.playerConnections")}</span><strong>{status.hostPeers.length}</strong>
          </div>
          {#each status.hostPeers as peer (peer.id)}<div class="host-peer-row">
              <code
                >{peer.id.length > 18
                  ? `${peer.id.slice(0, 10)}...${peer.id.slice(-6)}`
                  : peer.id}</code
              ><span
                >{peer.route === "direct"
                  ? t("join.direct")
                  : peer.route === "relay"
                    ? t("join.relay")
                    : t("join.detecting")}</span
              ><strong>{peer.rttMs == null ? "--" : `${peer.rttMs} ms`}</strong>
            </div>{/each}
        </section>{/if}
      <div class="connection-footer">
        <p>{status.message ? backendMessage(status.message) : t("create.ready")}</p>
        <Button variant="danger" disabled={pending} loading={pending} onclick={stopRoom}
          ><Square size={15} />{t("create.stop")}</Button
        >
      </div>
    </section>
  {:else}
    <section class="create-panel">
      <div class="form-field">
        <span class="field-label">{t("create.minecraftPort")}</span><Select
          class="settings-select"
          value={portMode}
          options={portOptions}
          onValueChange={setPortMode}
        />
      </div>
      {#if portMode === "auto"}<div class="discovery-row">
          <div
            class:detected={scan.port != null}
            class:failed={!!scanError}
            class="discovery-state"
          >
            <div>
              <strong
                >{scan.port != null
                  ? `${t("create.portFoundLabel")} ${scan.port}`
                  : scanError
                    ? t("create.discoveryFailed")
                    : t("create.discovering")}</strong
              ><span
                >{scan.port != null ? t("create.worldReady") : t("create.waitingBroadcast")}</span
              >
            </div>
          </div>
          <span
            class:detected={scan.port != null}
            class:failed={!!scanError}
            class="discovery-status-icon"
            >{#if scan.port != null}<CircleCheck size={20} />{:else if scanError}<CircleAlert
                size={19}
              />{:else}<LoaderCircle class="spin" size={19} />{/if}</span
          >
        </div>{:else}<div class="form-field manual-port-field">
          <label for="host-port" class="field-label">{t("create.port")}</label><Input
            id="host-port"
            class="room-input"
            bind:value={manualPort}
            type="number"
            min={1}
            max={65535}
            hideNumberControls
          />
        </div>{/if}
      <div class="form-field settings-field">
        <label for="max-players" class="field-label">{t("create.maxPlayers")}</label><Input
          id="max-players"
          class="room-input"
          bind:value={maxPlayers}
          type="number"
          min={1}
          max={1000}
          placeholder={t("create.unlimited")}
          hideNumberControls
        />
      </div>
      <div class="form-field">
        <span class="field-label">{t("create.uriLifetime")}</span><Select
          class="settings-select"
          value={uriLifetime}
          options={lifetimeOptions}
          onValueChange={(value) => onLifetime(value as HostUriLifetime)}
        />
      </div>
      <div class="create-actions">
        {#if commandError || occupied || status.message}<p class="field-error">
            {occupied ? t("create.occupied") : commandError || backendMessage(status.message)}
          </p>{/if}<Button
          class="primary-button"
          disabled={!canCreate}
          loading={pending}
          onclick={createRoom}><HousePlus size={17} />{t("create.create")}</Button
        >
      </div>
    </section>
  {/if}
</div>

// src/components/rooms/HostView.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { Cmz_Button, Cmz_Input, Cmz_Select, type SelectOption } from "cmzya-modern-ui";
import {
  getLanScan,
  probeHostPort,
  startHost,
  startLanScan,
  stopLanScan,
  stopTunnel,
  type LanScanSnapshot,
} from "@api";
import type { HostUriLifetime } from "../../models/preferences";
import type { ConnectStatus } from "../../models/tunnel";
import { backendMessage, t } from "../../i18n";
import {
  Check,
  CircleAlert,
  CircleCheck,
  Copy,
  HousePlus,
  LoaderCircle,
  Square,
} from "@lucide/vue";

const props = defineProps<{
  status: ConnectStatus;
  uriLifetime: HostUriLifetime;
}>();
const emit = defineEmits<{
  changeUriLifetime: [value: HostUriLifetime];
}>();

const portMode = ref<"auto" | "manual">("auto");
const manualPort = ref("25565");
const maxPlayers = ref("");
const scan = ref<LanScanSnapshot>({ scanning: false, port: null });
const scanError = ref("");
const commandError = ref("");
const pending = ref(false);
const copied = ref(false);
let scanTimer: number | null = null;
let monitorTimer: number | null = null;
const portModeOptions = computed<SelectOption[]>(() => [
  { label: t("create.automaticDiscovery"), value: "auto" },
  { label: t("create.manual"), value: "manual" },
]);
const uriLifetimeOptions = computed<SelectOption[]>(() => [
  { label: t("create.lifetimeAlways"), value: "always" },
  { label: t("create.lifetimeNever"), value: "never" },
  { label: t("create.lifetime1h"), value: "1h" },
  { label: t("create.lifetime3h"), value: "3h" },
  { label: t("create.lifetime6h"), value: "6h" },
  { label: t("create.lifetime12h"), value: "12h" },
  { label: t("create.lifetime24h"), value: "24h" },
]);

const hosting = computed(() => props.status.mode === "host" && props.status.phase !== "idle");
const occupied = computed(() => props.status.phase !== "idle" && props.status.mode !== "host");
const selectedPort = computed(() =>
  portMode.value === "auto" ? scan.value.port : Number(manualPort.value),
);
const validPort = computed(() => {
  const port = selectedPort.value;
  return Number.isInteger(port) && port != null && port >= 1 && port <= 65535;
});
const validMaxPlayers = computed(() => {
  if (maxPlayers.value.trim() === "") return true;
  const count = Number(maxPlayers.value);
  return Number.isInteger(count) && count >= 1 && count <= 1000;
});
const canCreate = computed(
  () => !pending.value && !occupied.value && validPort.value && validMaxPlayers.value,
);
const localizedStatusMessage = computed(() =>
  props.status.message ? backendMessage(props.status.message) : null,
);

function setPortMode(value: string | number) {
  if (value !== "auto" && value !== "manual") return;
  portMode.value = value;
  if (value === "auto") void beginScan(true);
  else void stopScan();
}

function setUriLifetime(value: string | number) {
  if (!uriLifetimeOptions.value.some((option) => option.value === value)) return;
  emit("changeUriLifetime", value as HostUriLifetime);
}

async function beginScan(restart = false) {
  stopMonitoring();
  scanError.value = "";
  try {
    scan.value = await startLanScan(restart);
    startPolling();
  } catch (error) {
    scanError.value = backendMessage(error);
  }
}

function startPolling() {
  if (scanTimer != null) return;
  scanTimer = window.setInterval(async () => {
    try {
      scan.value = await getLanScan();
      if (scan.value.port != null) {
        stopPolling();
        startMonitoring();
      } else if (!scan.value.scanning) {
        stopPolling();
      }
    } catch (error) {
      scanError.value = backendMessage(error);
      stopPolling();
    }
  }, 800);
}

function startMonitoring() {
  if (monitorTimer != null) return;
  monitorTimer = window.setInterval(async () => {
    const port = scan.value.port;
    if (port == null) return;
    try {
      const available = await probeHostPort(port);
      if (!available) void beginScan(true);
    } catch (error) {
      scanError.value = backendMessage(error);
    }
  }, 5000);
}

function stopMonitoring() {
  if (monitorTimer != null) {
    window.clearInterval(monitorTimer);
    monitorTimer = null;
  }
}

function stopPolling() {
  if (scanTimer != null) {
    window.clearInterval(scanTimer);
    scanTimer = null;
  }
}

async function stopScan() {
  stopPolling();
  stopMonitoring();
  scan.value = { scanning: false, port: null };
  try {
    await stopLanScan();
  } catch (error) {
    scanError.value = backendMessage(error);
  }
}

async function createRoom() {
  if (!canCreate.value || selectedPort.value == null) return;
  pending.value = true;
  commandError.value = "";
  try {
    await startHost(
      selectedPort.value,
      maxPlayers.value.trim() === "" ? null : Number(maxPlayers.value),
      props.uriLifetime,
    );
  } catch (error) {
    commandError.value = backendMessage(error);
  } finally {
    pending.value = false;
  }
}

async function stopRoom() {
  pending.value = true;
  commandError.value = "";
  try {
    await stopTunnel();
  } catch (error) {
    commandError.value = backendMessage(error);
  } finally {
    pending.value = false;
  }
}

async function copyInvite() {
  if (!props.status.shareUri) return;
  await navigator.clipboard.writeText(props.status.shareUri);
  copied.value = true;
  window.setTimeout(() => (copied.value = false), 1600);
}

onMounted(() => {
  if (props.status.phase === "idle") void beginScan();
});

watch(
  () => props.status.phase,
  (phase, previous) => {
    if (phase === "idle" && previous !== "idle" && portMode.value === "auto") {
      void beginScan(true);
    } else if (phase !== "idle") {
      void stopScan();
    }
  },
);

onUnmounted(() => {
  stopPolling();
  stopMonitoring();
  void stopLanScan().catch((error) => {
    console.error("Failed to stop LAN scan", error);
  });
});
</script>

<template>
  <div class="workspace create-workspace">
    <section class="intro">
      <div>
        <h1>{{ hosting ? t("create.running") : t("create.title") }}</h1>
        <p v-if="hosting">{{ t("create.runningHint") }}</p>
        <p v-else>{{ t("create.idleHint") }}</p>
      </div>
      <span class="phase-pill" :class="status.phase">
        {{
          hosting
            ? status.phase === "active"
              ? t("create.created")
              : t("create.processing")
            : t("create.notCreated")
        }}
      </span>
    </section>

    <section v-if="hosting" class="connection-panel host-panel">
      <div class="share-block">
        <span>{{ t("create.invite") }}</span>
        <strong>{{ status.shareUri ?? t("create.generatingInvite") }}</strong>
        <Cmz_Button
          class="copy-button"
          variant="outline"
          type="button"
          :disabled="!status.shareUri"
          @click="copyInvite"
        >
          <Check v-if="copied" :size="16" />
          <Copy v-else :size="16" />
          {{ copied ? t("create.copied") : t("create.copyInvite") }}
        </Cmz_Button>
      </div>
      <div class="host-summary">
        <div>
          <span>{{ t("create.players") }}</span>
          <strong>{{ status.playerCount }}</strong>
        </div>
        <div>
          <span>{{ t("create.targetPort") }}</span>
          <strong>{{ status.hostPort ?? "--" }}</strong>
        </div>
      </div>
      <div class="connection-footer">
        <p>{{ localizedStatusMessage ?? t("create.ready") }}</p>
        <Cmz_Button
          class="danger-button"
          variant="outline"
          type="button"
          :disabled="pending"
          :loading="pending"
          @click="stopRoom"
        >
          <Square :size="15" />{{ t("create.stop") }}
        </Cmz_Button>
      </div>
    </section>

    <section v-else class="create-panel">
      <div class="form-field">
        <span class="field-label">{{ t("create.minecraftPort") }}</span>
        <Cmz_Select
          class="settings-select"
          :model-value="portMode"
          :options="portModeOptions"
          @update:model-value="setPortMode"
        />
      </div>

      <div v-if="portMode === 'auto'" class="discovery-row">
        <div class="discovery-state" :class="{ detected: scan.port != null, failed: scanError }">
          <div>
            <strong v-if="scan.port != null">
              {{ t("create.portFoundLabel") }}
              <span class="detected-port">{{ scan.port }}</span>
            </strong>
            <strong v-else>{{
              scanError ? t("create.discoveryFailed") : t("create.discovering")
            }}</strong>
            <span>{{
              scan.port != null ? t("create.worldReady") : t("create.waitingBroadcast")
            }}</span>
          </div>
        </div>
        <span
          class="discovery-status-icon"
          :class="{ detected: scan.port != null, failed: scanError }"
          :title="
            scan.port != null
              ? t('create.portFoundLabel')
              : scanError
                ? t('create.discoveryFailed')
                : t('create.discovering')
          "
          aria-hidden="true"
        >
          <CircleCheck v-if="scan.port != null" :size="20" />
          <CircleAlert v-else-if="scanError" :size="19" />
          <LoaderCircle v-else class="spin" :size="19" />
        </span>
      </div>

      <div v-else class="form-field manual-port-field">
        <label for="host-port" class="field-label">{{ t("create.port") }}</label>
        <Cmz_Input
          id="host-port"
          class="room-input"
          v-model="manualPort"
          type="number"
          :min="1"
          :max="65535"
          :hide-number-controls="true"
        />
      </div>

      <div class="form-field settings-field">
        <label for="max-players" class="field-label">{{ t("create.maxPlayers") }}</label>
        <Cmz_Input
          id="max-players"
          class="room-input"
          v-model="maxPlayers"
          type="number"
          :min="1"
          :max="1000"
          :hide-number-controls="true"
          :placeholder="t('create.unlimited')"
        />
      </div>

      <div class="form-field">
        <span class="field-label">{{ t("create.uriLifetime") }}</span>
        <Cmz_Select
          class="settings-select"
          :model-value="uriLifetime"
          :options="uriLifetimeOptions"
          @update:model-value="setUriLifetime"
        />
      </div>

      <div class="create-actions">
        <p v-if="commandError || occupied || status.message" class="field-error">
          {{ occupied ? t("create.occupied") : commandError || localizedStatusMessage }}
        </p>
        <Cmz_Button
          class="primary-button"
          type="button"
          :disabled="!canCreate"
          :loading="pending"
          @click="createRoom"
        >
          <HousePlus :size="17" />
          {{ t("create.create") }}
        </Cmz_Button>
      </div>
    </section>
  </div>
</template>
